export const SET_LANGUAGE = 'SET_LANGUAGE';

export const ADD_GROUPNAME = 'ADD_GROUPNAME';
export const SET_COLLECTION_TYPE = 'SET_COLLECTION_TYPE';
export const ADD_TO_COLLECTION = 'ADD_TO_COLLECTION';
export const EDIT_COLLECTION_ITEM = 'EDIT_COLLECTION_ITEM';
export const DELETE_FROM_COLLECTION = 'DELETE_FROM_COLLECTION';

export const RESET = 'RESET';
