export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_ANALISYS_TYPE = 'SET_ANALISYS_TYPE';
export const SET_HEADER_DATA = 'SET_HEADER_DATA';

export const SET_TEMPLATES = 'SET_TEMPLATES';
export const SET_ANALISYS_RESULT = 'SET_ANALISYS_RESULT';
